---
title: "P8105 HOMEWORK1"
author: "Junhui Mi"
date: 2019-09-14
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
```

The purpose of this file is to present a couple of basic plots using `ggplot`.

First we create a dataframe containing variables for our plots.

```{r df_1_create}
df_1 = tibble(
  norm_samp = rnorm(8),
  norm_samp_pos = norm_samp > 0,
  chara <- c("A", "B", "C", "D", "E", "F", "G", "H"),
  fact <- factor(c("data", "biostat", "epi", "biostat", "data", "biostat",
                   "data","data"), levels = c("data", "epi", "biostat"))
)
```



Then we create a dataframe containing variables for our plots.

```{r df_2_create}
df_2 = tibble(
  x = rnorm(500),
  y = rnorm(500),
  logi = x + y > 1,
  num = as.numeric(logi),
  fac = as.factor(logi)
)
```

Next we show a scatterplot of `y` vs `x`. 

```{r yx_scatter}
ggplot(df_2, aes(x = x, y = y, color = df_2$logi)) + geom_point()
ggplot(df_2, aes(x = x, y = y, color = df_2$num)) + geom_point()
ggplot(df_2, aes(x = x, y = y, color = df_2$fac)) + geom_point()
```